Repository Software-Engineering-Project-PKHSAK/URL-Shortener-2.0, pull requests merged in 2024-11, with the labels that each got.

#3 resolves #2: correcting redirection for non fully qualified urls
  backend/src/routes/links.py
Labels: bug

#7 resolves #6: adding copy QR feature
  frontend/src/screens/DashboardScreens/LinkCardItem.tsx
Labels: enhancement

#8 adding null checks for edit link
  frontend/src/screens/DashboardScreens/Drawers/UpdateLinkDrawer.tsx
Labels: bug

#10 resolves #9: moving engagement creation to backend
  backend/src/routes/links.py
  frontend/src/screens/DashboardScreens/RedirectionPage.tsx
Labels: bug

#17 resolves #16: collecting device details as part of engagement in backend
  backend/migrations/versions/27f205401f42_adding_device_properties_to_engagement.py
  backend/migrations/versions/78fdf7999b86_add_tags_column_to_link_model.py
  backend/requirements.txt
  backend/src/models/engagements.py
  backend/src/routes/links.py
  frontend/.env
  frontend/.gitignore
Labels: enhancement

#24 resolves #23: using JWT token for resource authorization
  backend/src/models/user.py
  backend/src/routes/auth.py
  backend/src/routes/links.py
  frontend/src/api/createBulkLinks.ts
  frontend/src/api/createLink.ts
  frontend/src/api/deleteLink.ts
  frontend/src/api/fetchLinkEngagements.ts
  frontend/src/api/fetchLinks.ts
  frontend/src/api/fetchLinksByTags.ts
  frontend/src/api/fetchStats.ts
  frontend/src/api/updateLink.ts
  frontend/src/screens/AuthScreens/Login.tsx
  frontend/src/screens/DashboardScreens/Dashboard.tsx
  frontend/src/screens/DashboardScreens/EditUser.tsx
  frontend/src/screens/DashboardScreens/LinkCardItem.tsx
Labels: enhancement

#27 resolves #26: adding visualizations for engagements in analytics drawer
  frontend/src/screens/DashboardScreens/Drawers/ViewLinkDrawer.tsx
  frontend/src/screens/DashboardScreens/LinkCardItem.tsx
Labels: enhancement

#29 resolves #28: re-rendering charts on every drawer open
  frontend/src/screens/DashboardScreens/Drawers/CreateLinkDrawer.tsx
  frontend/src/screens/DashboardScreens/Drawers/ViewLinkDrawer.tsx
Labels: bug

#30 Prateek update
  README.md
  Rubric/rubric.md
  backend/Documentation/Readme.md
  backend/README.md
Labels: documentation

#34 Updated Citations
  CITATION.cff
  README.md
Labels: documentation

#38 Contributors badge added
  .github/workflows/Coverage.yml
  README.md
Labels: documentation

#40 Badges completely updated
  README.md
Labels: documentation

#42 Prateek update
  LICENSE
  backend/Documentation/app.py
  backend/Documentation/auth.py
  backend/Documentation/genindex.html
  backend/Documentation/index.html
  backend/Documentation/links.py
  backend/Documentation/py-modindex.html
  backend/Documentation/search.html
  backend/conf.py
  backend/src/app.py
  backend/src/config.py
  backend/src/extensions.py
  backend/src/models/engagements.py
  backend/src/models/links_anonymous.py
  backend/src/models/user.py
  backend/src/routes/auth.py
Labels: documentation

#43 adding editorconfig
  backend/.editorconfig
Labels: good first issue

#46 Added Test cases to bulk link and click limits
  backend/test/test_bulk_link.py
  backend/test/test_link_clicks_limit.py
Labels: enhancement

#49 Added Poster for this project
  poster/G53_Akarsh_Himanshu_Prateek_Software_Engineering_Poster_URL_Shortener.png
Labels: documentation

#50 Added Target audiences in Readme
  README.md
Labels: documentation

#52 adding linters and rubric
  .github/workflows/autopep8.yml
  .github/workflows/pyflakes.yml
  README.md
  Rubric/rubric.md
Labels: documentation

#53 added test for tags and bulk links
  backend/test/test_tags.py
  backend/test/tests_bulklink.py
Labels: enhancement

#54 adding feature gifs
  README.md
  phase_4_gifs/ab_test.gif
  phase_4_gifs/copy_qr.gif
  phase_4_gifs/dashboard_analytics.gif
  phase_4_gifs/jwt_auth.gif
  phase_4_gifs/validate_stub.gif
Labels: documentation

#56 updated promo video
  README.md
Labels: documentation

#55 adding test workflow
  .github/workflows/python-tests.yml
  README.md
  Rubric/rubric.md
  backend/src/config.py
Labels: enhancement

#57 correcting tests
  README.md
  backend/test/test_tags.py
Labels: bug
